language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - development

cache:
  directories:
    - node_modules
    
before_script:
  - npm install -g @angular/cli
  
install:
  - npm install

script:
  - ng lint
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fitness-tracker
  on:
    branch: development